port: "8080"

db:
  driver_name: "postgres"
  host: "postgres"
  port: "5432"
  username: "postgres"
  password: "qwerty"
  dbname: "postgres"
  sslmode: "disable"

tables:
  user_table: "users"
  quest_table: "quest"
  history_table: "history"